export { default as NextLink } from "./next-link";
export { default as Wrapper } from "./wrapper";
export { default as RegWrapper } from "./reg-wrapper";
export { default as ProfileWrapper } from "./profile-wrapper";
export { default as Pagination } from "./pagination";
export { default as RightInfoAll } from "./right-info-all";
export { default as LeftInfoAll } from "./left-info-all";
export { default as MobileNavigation } from "./mobile-navigation";
export { default as Rates } from "./rates";
